# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshed < Formula
  desc ""
  homepage "https://github.com/trntv/sshed"
  version "1.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/trntv/sshed/releases/download/1.2.0/sshed_1.2.0_darwin_amd64.tar.gz"
    sha256 "9dc952dc997e6bff4b3ff212a77a398583c64a156db531fbfd04f41c5f9baa06"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/trntv/sshed/releases/download/1.2.0/sshed_1.2.0_linux_amd64.tar.gz"
    sha256 "2a2671ba7b5462a557660d21a863cb565ffe79a53bab124bb4b1cd84b1d8c164"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/trntv/sshed/releases/download/1.2.0/sshed_1.2.0_linux_armv6.tar.gz"
    sha256 "5c4fcd5c128e8f04bcd01f01b6665c9f61dabe825cc1c13b4e2b5dfc9ecfb3ad"
  end

  def install
    bin.install "sshed"
    bash_completion.install "completions/autocomplete.sh"
  end
end
