# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshed < Formula
  desc ""
  homepage "https://github.com/trntv/sshed"
  version "1.2.0-alpha-3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/trntv/sshed/releases/download/1.2.0-alpha-3/sshed_1.2.0-alpha-3_darwin_amd64.tar.gz"
    sha256 "2f93bb9cd4a389a112cb47b5f8fc4d9f32d1fe43b4e4e213036188e8877dcc4e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/trntv/sshed/releases/download/1.2.0-alpha-3/sshed_1.2.0-alpha-3_linux_amd64.tar.gz"
    sha256 "df87f0b28c4e6f9c812ed055eaceba99e0d830ce782495eb32deed28091532d5"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/trntv/sshed/releases/download/1.2.0-alpha-3/sshed_1.2.0-alpha-3_linux_armv6.tar.gz"
    sha256 "84285121b25b976ad7bc9a0b1396cc524b2fb43dc7659f14de9464683680d32c"
  end

  def install
    bin.install "sshed"
    bash_completion.install "completions/autocomplete.sh"
  end
end
